version: '3.8'

services:
  web_mini_project:
    build:
      context: ./docker
      dockerfile: web_mini_project/Dockerfile
    ports:
      - ${DOCKER_WEB_MINI_PROJECT_HOST_PORT}:6060
    env_file:
      - .env
    volumes:
      - .:/go/src/github.com/salehrashid/mini-project
