version: '3.8'

services:
  web_mini_project:
    build:
      context: ./docker
      dockerfile: web_mini_project/Dockerfile
    ports:
      - ${DOCKER_WEB_MINI_PROJECT_HOST_PORT}:6060
    env_file:
      - .env
    volumes:
      - .:/go/src/github.com/salehrashid/mini-project
  
  postgresql:
    image: postgres:latest
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    ports:
      - "${DOCKER_POSTGRESQL_HOST_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  migrate:
    image: migrate/migrate
    entrypoint: ["migrate", "-path", "scripts/sql", "-database", "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgresql:${DOCKER_POSTGRESQL_HOST_PORT}/${POSTGRES_DATABASE}?sslmode=disable", "up"]
    volumes:
      - ./scripts/sql:/scripts/sql
    depends_on:
      - postgresql

volumes:
  postgres_data:
